'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import AuthBackground from '@/components/auth/AuthBackground';
import Link from 'next/link';
import { ShieldAlert, Loader2, ArrowRight, ArrowLeft } from 'lucide-react';

export default function VerifyOtpPage() {
  const router = useRouter();

  const [otpValues, setOtpValues] = useState<string[]>(Array(6).fill(''));
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [resendTimer, setResendTimer] = useState(45);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  // Auto focus first input on mount
  useEffect(() => {
    document.getElementById('otp-0')?.focus();
  }, []);

  // Timer countdown
  useEffect(() => {
    if (resendTimer <= 0) return;
    const interval = setInterval(() => {
      setResendTimer((prev) => prev - 1);
    }, 1000);
    return () => clearInterval(interval);
  }, [resendTimer]);

  const triggerToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3000);
  };

  const handleOtpChange = (index: number, val: string) => {
    if (isNaN(Number(val))) return;
    const newValues = [...otpValues];
    newValues[index] = val.slice(-1);
    setOtpValues(newValues);

    // Auto-advance focus to next field
    if (val && index < 5) {
      document.getElementById(`otp-${index + 1}`)?.focus();
    }
  };

  const handleOtpKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    // Backspace shift focus backward
    if (e.key === 'Backspace' && !otpValues[index] && index > 0) {
      document.getElementById(`otp-${index - 1}`)?.focus();
    }
  };

  // Support pasting full 6-digit codes
  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    e.preventDefault();
    const pasteData = e.clipboardData.getData('text').trim();
    if (pasteData.length === 6 && !isNaN(Number(pasteData))) {
      const chars = pasteData.split('');
      setOtpValues(chars);
      document.getElementById('otp-5')?.focus();
    }
  };

  const handleVerify = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMsg(null);
    const code = otpValues.join('');

    if (code.length < 6) {
      setErrorMsg('Please enter the complete 6-digit verification code.');
      return;
    }

    setLoading(true);
    // Simulate OTP database check
    setTimeout(() => {
      setLoading(false);
      triggerToast('Two-factor authentication authorized!');
      setTimeout(() => {
        router.push('/dashboard');
      }, 1000);
    }, 1500);
  };

  const handleResend = () => {
    if (resendTimer > 0) return;
    setResendTimer(45);
    setOtpValues(Array(6).fill(''));
    triggerToast('A new 6-digit 2FA access code has been dispatched.');
    document.getElementById('otp-0')?.focus();
  };

  return (
    <main className="min-h-screen relative w-full overflow-hidden flex items-center justify-center p-6 sm:p-12">
      {/* 3D Aurora Mesh Backdrop */}
      <AuthBackground />

      {/* Glass Card Container */}
      <div className="relative z-10 w-full max-w-[420px] glass-premium rounded-3xl p-8 sm:p-10 border border-slate-200/50 dark:border-white/5 shadow-2xl text-left backdrop-blur-xl">
        
        {/* Title */}
        <div className="text-center mb-8">
          <span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-blue-500/10 text-blue-600 dark:text-cyan-400 mb-4">
            <ShieldAlert size={22} />
          </span>
          <h2 className="text-2xl font-black text-slate-950 dark:text-white">Two-Factor Authentication</h2>
          <p className="mt-2 text-xs font-semibold leading-5 text-slate-500 dark:text-slate-400">
            Enter the 6-digit access code generated by your authenticator app to authorize session access.
          </p>
        </div>

        {/* Error Notification */}
        {errorMsg && (
          <div className="mb-5 rounded-xl border border-rose-500/20 bg-rose-500/10 p-3.5 text-xs font-bold text-rose-600 dark:text-rose-400">
            {errorMsg}
          </div>
        )}

        {/* Form */}
        <form onSubmit={handleVerify} className="space-y-6">
          <div className="flex justify-between gap-2.5">
            {otpValues.map((val, idx) => (
              <input
                key={idx}
                id={`otp-${idx}`}
                type="text"
                maxLength={1}
                value={val}
                onChange={(e) => handleOtpChange(idx, e.target.value)}
                onKeyDown={(e) => handleOtpKeyDown(idx, e)}
                onPaste={idx === 0 ? handlePaste : undefined}
                className="w-12 h-12 text-center rounded-xl border border-slate-200/50 dark:border-white/5 bg-white/40 dark:bg-slate-900/30 text-lg font-black text-slate-900 dark:text-white outline-none focus:border-blue-500 dark:focus:border-cyan-400 transition"
              />
            ))}
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-2.5 rounded-xl bg-gradient-to-r from-blue-600 to-indigo-650 text-white text-xs font-black uppercase tracking-[0.14em] shadow-lg shadow-blue-500/20 hover:opacity-95 transition disabled:opacity-50 flex items-center justify-center gap-2"
          >
            {loading ? (
              <>
                <Loader2 size={13} className="animate-spin" />
                Authorizing...
              </>
            ) : (
              <>
                Authorize Session
                <ArrowRight size={13} />
              </>
            )}
          </button>
        </form>

        {/* Footer controls */}
        <div className="mt-8 flex items-center justify-between text-xs font-bold text-slate-500 border-t border-slate-200/30 dark:border-white/5 pt-5">
          <Link href="/login" className="inline-flex items-center gap-1 hover:text-slate-700">
            <ArrowLeft size={13} />
            Back to Sign In
          </Link>
          <button
            type="button"
            onClick={handleResend}
            disabled={resendTimer > 0}
            className={`font-black uppercase tracking-wider ${
              resendTimer > 0 ? 'text-slate-400 cursor-default' : 'text-blue-600 dark:text-cyan-400 hover:underline'
            }`}
          >
            {resendTimer > 0 ? `Resend in ${resendTimer}s` : 'Resend Code'}
          </button>
        </div>

      </div>

      {/* Toast Alert */}
      {toastMessage && (
        <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 rounded-2xl bg-slate-950 px-4 py-3 text-xs font-black text-white shadow-2xl border border-white/10 slide-up">
          <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-ping" />
          {toastMessage}
        </div>
      )}
    </main>
  );
}
